"""updated authors

Revision ID: 237e517962a2
Revises: 3ef65030e99e
Create Date: 2024-08-08 16:31:50.563337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237e517962a2'
down_revision: Union[str, None] = '3ef65030e99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'created_by_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'created_by_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
