"""when user deleted, books and authors do not cascade

Revision ID: 3ef65030e99e
Revises: 2587f4cb9c7f
Create Date: 2024-08-08 16:28:41.154207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef65030e99e'
down_revision: Union[str, None] = '2587f4cb9c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
