"""updated createdbyuser to managedbyuser

Revision ID: 4d6bdb4a8099
Revises: d389796c9672
Create Date: 2024-08-08 18:28:15.046794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6bdb4a8099'
down_revision: Union[str, None] = 'd389796c9672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('managed_by_user', sa.Integer(), nullable=True))
    op.drop_constraint('authors_created_by_user_fkey', 'authors', type_='foreignkey')
    op.create_foreign_key(None, 'authors', 'users', ['managed_by_user'], ['id'], ondelete='SET NULL')
    op.drop_column('authors', 'created_by_user')
    op.add_column('books', sa.Column('managed_by_user', sa.Integer(), nullable=True))
    op.drop_constraint('books_created_by_user_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['managed_by_user'], ['id'], ondelete='SET NULL')
    op.drop_column('books', 'created_by_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_created_by_user_fkey', 'books', 'users', ['created_by_user'], ['id'], ondelete='SET NULL')
    op.drop_column('books', 'managed_by_user')
    op.add_column('authors', sa.Column('created_by_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.create_foreign_key('authors_created_by_user_fkey', 'authors', 'users', ['created_by_user'], ['id'], ondelete='SET NULL')
    op.drop_column('authors', 'managed_by_user')
    # ### end Alembic commands ###
