"""updated books

Revision ID: d389796c9672
Revises: 237e517962a2
Create Date: 2024-08-08 16:32:28.969666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd389796c9672'
down_revision: Union[str, None] = '237e517962a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'created_by_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'created_by_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
